name: slack-agent
kind: breeds
deployable:
  definition: magneticio/vamp-slack-agent:0.6.0-ve647-3
ports:
  webport: 8000/http
environment_variables:
  MESSAGE_TITLE_PREFIX                : 'UK:'
  VAMP_NAMESPACE                      : ${config://vamp.namespace}
  VAMP_KEY_VALUE_STORE_TYPE           : ${config://vamp.workflow-driver.workflow.vamp-key-value-store-type}
  VAMP_KEY_VALUE_STORE_CONNECTION     : ${config://vamp.workflow-driver.workflow.vamp-key-value-store-connection}
  VAMP_KEY_VALUE_STORE_TOKEN          : ${config://vamp.workflow-driver.workflow.vamp-key-value-store-token}
  VAMP_KEY_VALUE_STORE_PATH           : ${config://vamp.workflow-driver.workflow.vamp-key-value-store-path}
  VAMP_NSS_URL                        : nats://nats-streaming.vamp.svc.cluster.local:4222
  VAMP_NSS_CLIENT_ID                  : ${config://vamp.namespace}-slack-agent
  VAMP_NSS_CLUSTER_ID                 : vamp-streaming-cluster-london
  VAMP_NSS_USER                       : ${config://vamp.pulse.nats.username}
  VAMP_NSS_PASSWORD                   : ${config://vamp.pulse.nats.password}
  VAMP_NSS_TOKEN                      : XZek-mIYz-Fptm-d2L1-vLon
  VAMP_NSS_TLS_CA_CERT                : ${config://vamp.pulse.nats.ca-cert}
  VAMP_NSS_TLS_CLIENT_CERT            : ${config://vamp.pulse.nats.client-cert}
  VAMP_NSS_TLS_CLIENT_KEY             : ${config://vamp.pulse.nats.client-key}