apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../common/components/gateway-agent

#secretGenerator:
configMapGenerator:
- name: vamp-gateway-agent
  env: gateway-agent.env
