apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  io.vamp: vamp-gateway-agent

images:
- name: magneticio/vamp-gateway-agent
  newTag: 1.1.1

