vamp:
  persistence:
    database:
      type: mysql
      sql:
        database: vamp-${parent}
        table: ${namespace}
        user: vamp
        password: qnwK6EuiLLtr2w2F
        url: jdbc:mysql://35.204.16.95/vamp-${parent}
        database-server-url: jdbc:mysql://35.204.16.95
    key-value-store:
      type: vault
      base-path: /secret/vamp/${namespace}
      vault:
        url: ${env://VAMP_PERSISTENCE_KEY_VALUE_STORE_VAULT_URL}
        token: ${env://VAMP_PERSISTENCE_KEY_VALUE_STORE_VAULT_TOKEN}
    transformers:
      classes: []
  model:
    resolvers:
      deployment:
      - io.vamp.ee.model.DisabledConfigurationValueResolver
      namespace:
      - io.vamp.ee.model.NamespaceValueResolver
      workflow:
      - io.vamp.ee.model.WorkflowValueResolver
      - io.vamp.pulse.ElasticsearchValueResolver
  pulse:
    type: nats
    nats:
      url: nats://nss.amsterdam.kmt-example.vamp.cloud:4222
      cluster-id: vamp-streaming-cluster-amsterdam
      client-id: vamp-backend
      token: XZek-mIYz-Fptm-d2L1-vAms
    elasticsearch:
      index:
        name: vamp-pulse-${namespace}
      url: http://es.amsterdam.kmt-example.vamp.cloud:9200
  container-driver:
    type: kubernetes
    kubernetes:
      url: https://34.90.46.183
      bearer: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tdzcyeHgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijg0OGJiYjZiLTgzMTktMTFlOS1hN2VjLTQyMDEwYWE0MDBjOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.ZJEH4DmT2z4KEbfuNSh-YaCqGuP9R5cyIxGmQOcn-H2GqMpnE2SNQrK-vHnpywsXdahLEJOhPl06avURIpVG4tmJFzEqcxLbtwzfYL4aWg7ldXY7QIeIINB9DM8FBVQTWFXRMZksSEhaS26HFeGIEfYagFYwciPlnmtm8TznJ3jJo3g_Zbblir9BH94EdZycdLy2iVVpn1BJiZIvm8Etp6Jk_4oGvLc5iNRmH-M7o73lRmYt74_0amsmf6HJ6Nlf_49XBi8waFUWCMbkLtmiX1ugkqovdaYlnxQ6jX1lKtbqNL4FMdUtY2q5wID9pKU2uaVo-DfzNNyqdBqffOdygA
      vamp-gateway-agent-id: vamp-gateway-agent
      tls-check: false
      namespace: nl-production
  gateway-driver:
    marshallers:
    - type: haproxy
      name: "1.8"
      template:
        resource: /io/vamp/gateway_driver/haproxy/template.twig
  workflow-driver:
    workflow:
      vamp-elasticsearch-url: http://elasticsearch.vamp.svc.cluster.local:9200
      vamp-key-value-store-connection: ${env://VAMP_WORKFLOW_DRIVER_WORKFLOW_VAMP_KEY_VALUE_STORE_CONNECTION}
      vamp-key-value-store-path: /secret/vamp/${namespace}/workflows/${workflow}
      vamp-key-value-store-token: ${env://VAMP_WORKFLOW_DRIVER_WORKFLOW_VAMP_KEY_VALUE_STORE_TOKEN}
      vamp-key-value-store-type: vault
      vamp-url: http://vamp.kmt-example.vamp.cloud:8080
      vamp-workflow-execution-timeout: 60
      vamp-workflow-execution-period: 60
      deployables:
      - type: application/javascript
        breed: vamp-workflow-javascript
      scale:
        cpu: 0.1
        instances: 1
        memory: 128MB
    type: kubernetes
  operation:
    synchronization:
      period: 3 seconds
      check:
        health-checks: true
        deployable: true
        instances: true
        ports: true
        cpu: true
        environment-variables: true
        memory: true
      deployment:
        refetch-breed-on-update: true
    deployment:
      scale:
        cpu: 0.2
        instances: 1
        memory: 256MB
      arguments: []
    gateway:
      selector: namespace(${config://vamp.container-driver.kubernetes.namespace})
  metadata:
    namespace:
      title: production
