kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp:quantification:health-reader
rules:
- apiGroups: ["","apps"]
  resources: ["deployments","pods"]
  verbs: ["get","list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vamp-quantification
  namespace: default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp:quantification:health-reader
subjects:
- kind: ServiceAccount
  name: vamp-quantification
  namespace: default
roleRef:
  kind: ClusterRole
  name: vamp:quantification:health-reader
  apiGroup: rbac.authorization.k8s.io